name: Vagrant Ruby Tests
on:
  push:
    branches:
      - main
      - 'test-*'
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'plugins/**'
      - 'test/**'
      - 'templates/**'
      - 'Gemfile'
      - 'vagrant.gemspec'
      - 'Rakefile'
  pull_request:
    branches:
      - main
    paths:
      - 'bin/**'
      - 'lib/**'
      - 'plugins/**'
      - 'test/**'
      - 'Gemfile'
      - 'templates/**'
      - 'vagrant.gemspec'
      - 'Rakefile'
  workflow_dispatch:

jobs:
  unit-tests-ruby:
    runs-on: warp-ubuntu-latest-x64-4x;snapshot.key=warp-praj-vagrant-${{matrix.ruby}}
    continue-on-error: true
    strategy:
      matrix:
        ruby: [ '3.1', '3.2', '3.3' ]
    name: Vagrant unit tests on Ruby ${{ matrix.ruby }}
    steps:
      # - name: Code Checkout
      #   uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Ruby
        uses: ruby/setup-ruby@3783f195e29b74ae398d7caca108814bbafde90e # v1.180.1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      # - name: install dependencies
      #   run: sudo apt update && sudo apt -y install libarchive-tools
      - name: Run Tests
        run: bundle exec rake test:unit
      # - name: Create snapshot
      #   uses: WarpBuilds/snapshot-save@v1
      #   with:
      #     alias: 'warp-praj-vagrant-${{matrix.ruby}}'
      #     fail-on-error: true
      #     wait-timeout-minutes: 60
